import Head from "next/head";
import styles from "src/styles/Home.module.css";
import Map from "src/components/Map";
import Link from "next/link";
import Cookies from "js-cookie";
import { useRouter } from "next/router";
import { useState } from "react";

const Home = (props) => {
  // const [pins, setPins] = useState(
  //   props.pinsData.map((pin) => {
  //     return [pin.title, pin.lat, pin.lng];
  //   })
  // );
  const router = useRouter();

  //cookie情報確認用
  const button = () => {
    console.log(
      Cookies.get("uid"),
      Cookies.get("client"),
      Cookies.get("access-token")
    );
  };

  console.log(props);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <header className={styles.header}>
          <Link href={"/"}>OpenStreetWalk</Link>
          {props.isLogin ? (
            <div>
              <Link href={"/pins/new"}>ピン作成</Link>
              {"　"}
              <span className={styles.signout} onClick={props.authSignout}>
                ログアウト
              </span>
            </div>
          ) : (
            <div>
              <Link href={"/signin"}>ログイン</Link>
              {"　"}
              <Link href={"/signup"}>新規登録</Link>
            </div>
          )}
        </header>
        <main className={styles.main}>
          <Map pinsData={props.pinsData} />
          {/* <div className={styles.content}>
            <div>
              <table className={styles.table}>
                <thead>
                  <tr>
                    <th className={`${styles.table} ${styles.th}`}>title</th>
                    <th className={`${styles.table} ${styles.th}`}>緯度</th>
                    <th className={`${styles.table} ${styles.th}`}>経度</th>
                  </tr>
                </thead>
                {props.pinsData.length
                  ? props.pinsData.map((pin) => {
                      return (
                        <tbody key={pin.id}>
                          <tr>
                            <td className={`${styles.table} ${styles.th}`}>
                              {pin.title}
                            </td>
                            <td className={`${styles.table} ${styles.th}`}>
                              {pin.lat}
                            </td>
                            <td className={`${styles.table} ${styles.th}`}>
                              {pin.lng}
                            </td>
                          </tr>
                        </tbody>
                      );
                    })
                  : null}
              </table>
            </div>
          </div> */}
        </main>
        {/* <button onClick={button}>クッキー情報</button> */}
        <footer className={styles.footer}>footer</footer>
      </div>
    </>
  );
};

export const getServerSideProps = async () => {
  const url = "http://localhost:3000/pins";
  try {
    const res = await fetch(url);
    if (!res.ok) {
      throw new Error("ピンのデータ取得に失敗");
    }
    console.log("Success: ピンのデータを取得");
    const pins = await res.json();
    const pinsData = pins || null;
    return {
      props: {
        pinsData,
      },
    };
  } catch (error) {
    console.error(error);
    return {
      props: {
        pinsData: null,
      },
    };
  }
};

export default Home;
