import Head from "next/head";
import styles from "src/styles/Home.module.css";
import { SignIn } from "src/components/SignIn";
import Link from "next/link";

//ログインフォーム
const LogIn = (props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <header className={styles.header}>
          <Link href={"/"}>open-street-walk</Link>
        </header>
        <main className={styles.main}>
          <SignIn setIsLogin={props.setIsLogin} />
        </main>
        <footer className={styles.footer}>footer</footer>
      </div>
    </>
  );
};
export default LogIn;
