import Head from "next/head";
import styles from "src/styles/Home.module.css";
import Link from "next/link";
import { SignupForm } from "src/components/SignupForm/SignupForm";

const Signup = (props) => {
  return (
    <>
      <Head>
        <title>sign up - OpenStreetWalk</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <header className={styles.header}>
          <Link href={"/"} className={`${styles.logo} ${styles.button}`}>
            OpenStreetWalk
          </Link>
        </header>

        <main className={styles.main}>
          <SignupForm setIsLogin={props.setIsLogin} />
        </main>
      </div>
    </>
  );
};

export default Signup;
